//TRY --> Intentar ejecutar un c√≥digo y si nos da error nos lanza un error en el CATCH

try {
    console.log(pepito)
} catch (e) {
    console.log(e.message)   
}